<?php

/**
 * @file
 * A module to notify admin of new folks that have registered.
 * Created by: Drupalcon Denver Boston User Group BOF
 */

/**
 * Implementation of hook_user_insert
 * @see
 *  http://api.drupal.org/api/drupal/modules%21user%21user.api.php/function/hook_user_insert/7
 */
function register_notify_user_insert(&$edit, $account, $category) {

  // Paramaters we will pass to hook_mail.
  $params = array(
    'account' => $account,
    'site_name' => variable_get('site_name', ''),
  );

  $to = 'scottalanhenry@gmail.com';

  drupal_mail('register_notify', 'new_user', $to, user_preferred_language($account), $params);
}

/**
 * Implementation of hook_mail
 * @see
 *  http://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_mail/7
 */
function register_notify_mail($key, &$message, $params) {

  $account = $params['account'];

  $created = register_notify_time($account->created);

  $variables = array(
    '%site_name' => $params['site_name'],
    '%username' => $account->name,
    '%created' => $created,
    '%url' => $params['site_name'] . '/user/' . $account->uid,

  );

  switch ($key) {
    case 'new_user':
      $message['subject'] = t('An account has been created on @sitename', array('@sitename' => $params['site_name']));
      $message['body'][] = t('%username created an account %created. You can view %username\'s information at %url', $variables);
      break;
  }
}

/**
   * A function that will return a formatted time the user created their account.
   *
   * @param $timestamp
   *  The unix timestamp of when the user account was created.
   *
   * @return $date
   *  A formatted date and time.
   */
  function register_notify_time($timestamp) {
    $date = 'F, d Y';
    $time = 'g:i:s T';
    $format = $date . ' ' . $time;
    $created = date($format, $timestamp);
    return $created;
  }
